services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nudges
    expose: 
      - 5432
  nudges:
    environment:
      - SECRET_KEY=have-a-nice-day
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nudges
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8002 
    ports:
      - "8002:8002"
    depends_on:
      - db

volumes:
  postgres_data:
